name: Clone Stats Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Once a day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get clone stats
        id: getclones
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const res = await github.rest.repos.getClones({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return res.data;

      - name: Generate badge SVG
        run: |
          mkdir -p stats
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="150" height="20"><rect width="150" height="20" fill="#555"/><rect x="60" width="90" height="20" fill="#4c1"/><text x="30" y="14" fill="#fff" font-family="Verdana" font-size="11">Clones</text><text x="65" y="14" fill="#fff" font-family="Verdana" font-size="11">${{ fromJSON(steps.getclones.outputs.result).count }} (14d)</text></svg>' > stats/clones.svg

      - name: Commit badge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add stats/clones.svg
          git commit -m "Update clone stats badge"
          git push || echo "No changes"
