name: GitHub Clone Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get repo traffic data
        id: traffic
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const res = await github.rest.repos.getClones({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return res.data;

      - name: Save JSON file
        run: |
          mkdir -p stats
          echo '${{ steps.traffic.outputs.result }}' > stats/clones.json

      - name: Install Python and generate chart
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests
          python3 generate_chart.py

      - name: Commit chart
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add stats/
          git commit -m "Update traffic chart"
          git push || echo "No changes"
